services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresdb
    ports:
      - "5431:5432"
    volumes:
      - ./data:/var/lib/postgresql/data