POST http://127.0.0.1:8080/device/add
Content-Type: application/json

{
  "userId": 3,
  "name": "Airtag 3"
}

###
POST http://127.0.0.1:8080/device/add
Content-Type: application/json

{
  "userId": 14,
  "name": "Airtag 2"
}

###
GET http://127.0.0.1:8080/device/getAll/14
Content-Type: application/json

###
GET http://127.0.0.1:8080/device/15
Content-Type: application/json

###
DELETE http://127.0.0.1:8080/device/16
Content-Type: application/json

###
GET http://127.0.0.1:8080/device/getAll
Content-Type: application/json

###
DELETE http://127.0.0.1:8080/device/deleteAll
Content-Type: application/json
