POST http://127.0.0.1:8080/geofence/add
Content-Type: application/json

{
  "deviceId": 1
}

###
GET http://127.0.0.1:8080/geofence/1
Content-Type: application/json

###
DELETE http://127.0.0.1:8080/geofence/1
Content-Type: application/json

###
GET http://127.0.0.1:8080/geofence/device/1
Content-Type: application/json

###
DELETE http://127.0.0.1:8080/geofence/device/1
Content-Type: application/json

###
GET http://127.0.0.1:8080/geofence/getAll
Content-Type: application/json

###
DELETE http://127.0.0.1:8080/geofence/deleteAll
Content-Type: application/json