POST http://127.0.0.1:8080/vertex/add
Content-Type: application/json

{
  "geofenceId": 2,
  "latitude": "40.7128",
  "longitude": "-74.0060"
}

###
POST http://127.0.0.1:8080/vertex/add
Content-Type: application/json

{
  "geofenceId": 3,
  "latitude": "40.7129",
  "longitude": "-74.0061"
}

###
POST http://127.0.0.1:8080/vertex/add
Content-Type: application/json

{
  "geofenceId": 3,
  "latitude": "40.7130",
  "longitude": "-74.0062"
}

###
POST http://127.0.0.1:8080/vertex/add
Content-Type: application/json

{
  "geofenceId": 1,
  "latitude": "40.7131",
  "longitude": "-74.0063"
}

###
GET http://127.0.0.1:8080/vertex/1
Content-Type: application/json

###
DELETE http://127.0.0.1:8080/vertex/1
Content-Type: application/json

###
GET http://127.0.0.1:8080/vertex/getAll
Content-Type: application/json

###
DELETE http://127.0.0.1:8080/vertex/deleteAll
Content-Type: application/json

###
GET http://127.0.0.1:8080/vertex/getAll/2
Content-Type: application/json

###
DELETE http://127.0.0.1:8080/vertex/deleteAll/2
Content-Type: application/json
