POST http://127.0.0.1:8080/device/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoidXNlciIsImV4cCI6MzYwMDAwMTcxNDY2OTEwMX0.N8tAEyYuNep99-a6qeFMI1FSM4pN4JripmyJrqhUKUI

{
  "name": "Airtag 2"
}

###
DELETE http://127.0.0.1:8080/device/remove
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoidXNlciIsImV4cCI6MzYwMDAwMTcxNDY2OTEwMX0.N8tAEyYuNep99-a6qeFMI1FSM4pN4JripmyJrqhUKUI

{
  "name": "Airtag 3"
}

###
GET http://127.0.0.1:8080/device/getUserDevices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoidXNlciIsImV4cCI6MzYwMDAwMTcxNDY2OTEwMX0.N8tAEyYuNep99-a6qeFMI1FSM4pN4JripmyJrqhUKUI

###
GET http://127.0.0.1:8080/device/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjM2MDAwMDE3MTQ2NjA1NTV9.sz4ycqjliI8R5w1q74Vg7-KS1588bVnPOFPNDqOF_aM

###
DELETE http://127.0.0.1:8080/device/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjM2MDAwMDE3MTQ2NjA1NTV9.sz4ycqjliI8R5w1q74Vg7-KS1588bVnPOFPNDqOF_aM

###
GET http://127.0.0.1:8080/device/getAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjM2MDAwMDE3MTQ2NjA1NTV9.sz4ycqjliI8R5w1q74Vg7-KS1588bVnPOFPNDqOF_aM

###
DELETE http://127.0.0.1:8080/device/deleteAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjM2MDAwMDE3MTQ2NjA1NTV9.sz4ycqjliI8R5w1q74Vg7-KS1588bVnPOFPNDqOF_aM

###
DELETE http://127.0.0.1:8080/device/deleteAll/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjM2MDAwMDE3MTQ2NjA1NTV9.sz4ycqjliI8R5w1q74Vg7-KS1588bVnPOFPNDqOF_aM

