POST http://127.0.0.1:8080/user/register
Content-Type: application/json

{
  "username": "userDifferent",
  "password": "user"
}

###
POST  http://127.0.0.1:8080/user/login
Content-Type: application/json

{
  "username": "userDifferent",
  "password": "user"
}

###
GET http://127.0.0.1:8080/user/44
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoidXNlciIsImV4cCI6MzYwMDAwMTcxNTA5MTczNH0.OFTsH1rPSBxiLNS5rVJoPzd0_rLgMwjtCC2UZnId08c

###
PUT http://127.0.0.1:8080/user/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoidXNlciIsImV4cCI6MzYwMDAwMTcxNTA5MTczNH0.OFTsH1rPSBxiLNS5rVJoPzd0_rLgMwjtCC2UZnId08c

{
  "username": "user",
  "oldPassword": "user",
  "newPassword": "user"
}


### Admin calls
###
DELETE http://127.0.0.1:8080/user/81
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjM2MDAwMDE3MjgxNDYzOTJ9.lXZXqe1jKvXULlK91taBdNW3ZFG2r4Xdyzw_GZ4j4SE

###
DELETE http://127.0.0.1:8080/user/deleteAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjM2MDAwMDE3MjgxNDYzOTJ9.lXZXqe1jKvXULlK91taBdNW3ZFG2r4Xdyzw_GZ4j4SE
###
GET http://127.0.0.1:8080/user/getAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJudWxsIiwiaXNzIjoibnVsbCIsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjM2MDAwMDE3MjgxNDYzOTJ9.lXZXqe1jKvXULlK91taBdNW3ZFG2r4Xdyzw_GZ4j4SE